### ISSUE TITLE
USF PATS request - Add parking lot names to Geocoder

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#100]
A higher priority from USF PATS - they want us to add the parking lot names to the Geocoder, so someone can type in the lot name and have it show up (just like a building).

They will provide us with the lot names and lat/longs, so it should be fairly straightforward for us to add them.

I'm marking this for 10-24 milestone, although it may get pushed back if they don't provide us with the data before then.

@jailby Could you please work on this also, as soon as we get the data from them?

Thanks!

**Comment by barbeau** [comment]
Here's the first set of data from USF PATS for parking lot locations and names, in an Excel spreadsheet format:
[Paking Lot GPS.xlsx](https://github.com/CUTR-at-USF/usf-mobullity/files/42923/Paking.Lot.GPS.xlsx)

They will provide additional data as they create it.

**Comment by jailby** [comment]
I want to make sure of the naming convention.

The following is my opinion on the naming convention. When I will add the parking lots I will use these conventions. If you want to change anything just post here and I will follow the changes.

When the parking lot as an actual name:
"Actual name" example "Collins Garage" or "Apple"
When the parking lot is only designed by a number with an optional letter:
"Lot" then space then followed by the number of the lot and the optional letter (No space between the number and the letter).

example: "Lot 18B"
I choose no space between the number for consistency because the sign in real life don't have a space. Also, only a few parking lot in this excel spreadsheet have a space.

**Comment by barbeau** [comment]
@jailby That sounds good to me.  The only change I would make is for lots like "Apple", add a designation that its a parking lot.  So, something like `Apple (Parking lot)`.  Otherwise, from the auto-complete it won't be obvious if its a street name, building, or lot.

**Comment by jmfield2** [comment]
Also, see issue #213, and PR #226
https://github.com/CUTR-at-USF/usf-mobullity/blob/c2d2814dc1ed07ea2a878ff0e587cb08eb009435/opentripplanner-geocoder/src/main/resources/org/opentripplanner/geocoder/application-context.xml#L193
to
https://github.com/CUTR-at-USF/usf-mobullity/blob/c2d2814dc1ed07ea2a878ff0e587cb08eb009435/opentripplanner-geocoder/src/main/resources/org/opentripplanner/geocoder/application-context.xml#L318

Added several lots based on the public PATS parking map.  Many of those (including the permit types) were already somehow added to Google Maps.

**Comment by barbeau** [comment]
I think we can call this complete?  AFAIK we have all lot's in the Geocoder now.

**Comment by jmfield2** [comment]
Yes, all of the names listed in the spreadsheet are included in the geocoder.  I did not verify that the lat/lngs matched, but I assume they do.
