### ISSUE TITLE
Change colors to official USF colors

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#107]
The new USF logo is looking good:
https://github.com/CUTR-at-USF/usf-mobullity/pull/106#issuecomment-151530961

![image](https://cloud.githubusercontent.com/assets/928045/10791675/cbff2ab4-7d5f-11e5-8622-2d45c731d693.png)

However, it now clear that we aren't using official USF colors in the site - at least for the light green used for the widget headers and main header underline.

We should change to using just the official USF colors for green and gold, as defined here:
http://usfweb4.usf.edu/ucm/marketing/colors.aspx

Green is:

> PMS 342 C/PMS 342 CP
> CMYK: C93 M10 Y75 K43
> HTML: 006747
> RGB: R0 G103 B71

Gold is:

> PMS 4535 C/PMS 4535 CP
> CMYK: C6 M8 Y35 K12
> HTML: CFC493
> RGB: R207 G196 B147

**Comment by jailby** [comment]
Do you want both the light green and the green of the banner change to the usf official color green?

The fact there is two color seem more appealing. So we could also change the darker green to usf's green and the light green to the usf's gold.

I can change the code for multiple example and post screenshot of the result here.

Also, does this issue has an higher priority than the hamburger menu issue?

**Comment by barbeau** [comment]
Hamburger menu is higher priority than this.

My guy feeling is to keep the two-tone design, but change the lighter green to gold.  I'd give it a try with the combinations you think are best and post some screenshots here for comments.

**Comment by jailby** [comment]
Here are the colors used in the OneBusAway nav drawer, which I believe is consistent for standard Android design:

![image](https://cloud.githubusercontent.com/assets/928045/11039796/5d25b190-86d7-11e5-96a7-fc2e137b5139.png)

When an item with an icon is selected:
- Background color is set to `#11000000`
- Icon color is set to the theme color (for us, the USF green - `#006747`)
- Text color is set to the theme color (for us, the USF green - `#006747`)

When an item with an icon is NOT selected:
- Background color is set to white (`#ffffffff`)
- Icon color is set to `#888`
- Text color is set to black (`#ff000000`)

Separator is the color `#e5e5e5`.

Let's try these colors.

**Comment by jailby** [comment]
Latest comment on this:

1) The usf logo should probably be white to be consistent with the color of the menu's button.

2) The darker green should be changed to the usf green `#006747`

3) The light green should be changed to either the usf gold `#CFC493` or the usf green `#006747` depending on which one looks better.

4) The selection coloration (when a widget is opened the menu's button corresponding should be colored) depend on 3 and also on which one would look better between green & gold.

**Comment by barbeau** [comment]
According to http://usfweb4.usf.edu/ucm/marketing/colors.aspx, USF Gold hex is `#CFC493`.

**Comment by jailby** [comment]
1)

The following is a screenshot with the usf logo in white:
![image](https://cloud.githubusercontent.com/assets/1370401/12112531/1ec12dce-b36b-11e5-8c86-0513a6d4fdcf.png)

I like it but I would like to point out that this is **not** an [official USF logo](http://usfweb4.usf.edu/ucm/marketing/logos/logo-download.aspx). 

2)

I believe from [this line](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/style.css#L180) and its context (comment and variable names) that the darker green at the top is already the usf green.

3)
The color setting of the header of the **trip planner** and **layer** widgets can be found [here](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/style.css#L678).
The color setting of the light green ribbon can be found [here]().

The following is a screenshot is these color changed to usf **gold**:
![image](https://cloud.githubusercontent.com/assets/1370401/12113219/5061332a-b36f-11e5-948f-1394151dac3f.png)

The following is a screenshot is these color changed to usf **green**:
![image](https://cloud.githubusercontent.com/assets/1370401/12113263/9af773ae-b36f-11e5-8336-62bcc23279c7.png)

The following is a screenshot is the ribbon set to the usf **gold** and the header of the widgets to usf **green**:
![image](https://cloud.githubusercontent.com/assets/1370401/12113351/18dbe912-b370-11e5-9a0a-15088553e3dd.png)

I'm not really satisfied of any of the results. The best one is the **all usf green** one in my opinion. I'm going to experiment/think more and if I have something that I like I will post it.

The usf gold is close to some color used in the map so without a small black or white border around it I don't think it looks good and may hurt the visibility. This is why the "itinerary returned" box looks good but not the screenshot that I made using the usf gold color.

4)
This was separated in another [issue](https://github.com/CUTR-at-USF/usf-mobullity/issues/132). If the color need to be changed (e.g. to the usf gold) both [this color setting](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/style.css#L381) and [this one](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/style.css#L385) need to be changed.

**Comment by barbeau** [comment]
@jailby Thanks for looking at this!  I agree that the all USF green looks best, and I like the USF white logo.  Could you add a screenshot with how the all USF green looks on mobile?  If mobile looks good too, let's go with this combination.

**Comment by barbeau** [comment]
IMHO, we should also change the colors of the header of the minimized windows (i.e., "Layers" in the above screenshots) to match the open window - so, text would be white, and background color would be USF green.

**Comment by jailby** [comment]
The color setting of the headers background of the minimized windows can be found [here](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/style.css#L460).
The color setting for the text needed to be added.
The following is  a screenshot with the header background color changed to usf green and the text to white:
![image](https://cloud.githubusercontent.com/assets/1370401/12139423/7f6c5220-b42e-11e5-84a0-6eea071436d1.png)

The following screenshot is on mobile:
![image](https://cloud.githubusercontent.com/assets/1370401/12139515/01a573ac-b42f-11e5-92f1-f8ff800ff92a.png)

Also, after these change I believe that the only elements colored with the usf gold are:
- The itinerary returned box 
- The legend window 
- The send feed back window 
- (I might have forgot some)

For the first one I wasn't able to localize the code responsible for the color yet. 
For the last two the code can be found [here](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/style.css#L574) and [here](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/style.css#L582)

The fact there is only 3 elements with the usf gold might look odd.
@barbeau can I change these to have their text white with the usf green instead of the usf gold? Or does it look good as is?

**Comment by barbeau** [comment]
@jailby Looking good!  Yes, I would change the itinerary box, legend window, and send feedback window to all be white text on USF green.  I like the clean look of the green and white.

**Comment by jailby** [comment]
In the three following screenshot we can see that both the legend and send feedback window have their color changed.

Screenshot on desktop:
![image](https://cloud.githubusercontent.com/assets/1370401/12147515/58256ba0-b467-11e5-8f31-846a862b51c4.png)

Screenshot on mobile:
![image](https://cloud.githubusercontent.com/assets/1370401/12147904/77c1dcee-b469-11e5-8bd9-b11680e70d98.png)
![image](https://cloud.githubusercontent.com/assets/1370401/12147913/81c452b2-b469-11e5-8dca-d662505160ec.png)

In the two following screenshot we can see that the itinerary returned box has its color changed.

Screenshot on desktop:
![image](https://cloud.githubusercontent.com/assets/1370401/12147826/fb599944-b468-11e5-9164-8e5e33852b31.png)

Screenshot on mobile:
![image](https://cloud.githubusercontent.com/assets/1370401/12147847/1d4027f8-b469-11e5-9cc2-16105b83e63f.png)

I just noticed that on mobile the window of send feedback and the legend take all the screen. That's maybe an issue. The screenshots reflect the actual behavior (in term of size) on mobullity.forest.usf.edu/index.html

**Comment by jailby** [comment]
@barbeau this looks almost done but I noticed some things that we may want to change in term of color.

First the text in the layer widget is black whereas the text in the trip planner is the usf green. For the seek of consistency we may want them the same color?

Second all widgets have a "toolbox" associated which allow the user to minimize etc..
The following screenshot illustrate what I'm describing:
![image](https://cloud.githubusercontent.com/assets/1370401/12148045/37454ec0-b46a-11e5-8044-0f699f52e2fc.png)

IMHO, I think it look good. The hovering is the usf gold but this gold is not too far from the color of the map. To me it is not shocking.
I wanted to bring that up in case you want to change some color in this toolbox. Instead of the usf gold we could also put a light gray.

**Comment by barbeau** [comment]
@jailby Good catch.  I think black text everywhere in the body is probably best.  So, trip planner text would be changed to black.

I would also change the widget toolbox background color on hover to the same "selected" gray color we're using for the main menu to show that "Trip planner" or "Layers" is selected.  This way the "selected" item color is consistent.  And, if possible, the text on hover would change to the USF green - just like the main menu.  If it's difficult to do this you can keep the text the same color on hover.

**Comment by barbeau** [comment]
I also just noticed that the "TRIP PLANNER" text in the widget title bar is all upper-case, both when the trip planner widget is minimized and maximized.  We should change it to "Trip planner" to match the menu and case of the "Layers" widget.

![image](https://cloud.githubusercontent.com/assets/1370401/12147904/77c1dcee-b469-11e5-8bd9-b11680e70d98.png)

**Comment by jailby** [comment]
todo list:
- "TRIP PLANNER" to "Trip planner" _Done_
- trip planner body text should be black _Done_
- toolbox color change

@barbeau I'm sorry but can you explain me again the color change that you would like.

I'm confuse on your utilization of the word "selected". There is two gray in the menu. 
I believe that what you want is the lighter gray, right? If so no need to read the next paragraph.

The first one is a light gray that appearing when hovering an item. The second one appear when "pressing down" a button which is a darker gray (but still somewhat light). Also, when a widget is selected the button corresponding to the widget has a css class added call selected which is the usf green.

Also, the text is already colored with the usf green. So, I don't need to change anything unless I misunderstood what you meant.

**Comment by barbeau** [comment]
> I believe that what you want is the lighter gray, right?

Yes, correct - the gold below should be changed to light gray.

![image](https://cloud.githubusercontent.com/assets/928045/12154740/503d38e6-b48f-11e5-8903-b55e72cf0d80.png)

**Comment by jmfield2** [comment]
So, I looked at the screenshots and everything looks good but I noticed a couple of things that I don't think I saw mentioned above:

First, the tabs are mostly green but seem to have a slight border around the top that is a different color (the same as before, perhaps?) ... I believe this is from the border-radius or something similar.

Also, the color of the minimize and maximize buttons being all white seems wrong because of the shadow behind it that is now also white.  The shadow effect probably just needs to be removed.

**Comment by jailby** [comment]
Yes there is  a border around the tabs I noticed it and there is one around the itinerary window also (for example). I think they are either 3 or 1 pixel.

I wanted to talk about it in the next meeting we will have. I think it look better and kind of show a delimitation between the tab and the map. I think there should be one for the layer and trip planner widget as well as the top ribbon (the one who was light green).
Talking about the ribbon, I changed it to the usf green but I was wondering if we could delete it? I don't think it is useful and is a separate element from the top.

For the control button of all widget/window/tab I think they changed when I modified [this](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/style.css#L60) but I don't which attribute should change. This define white as the color for all text etc... which is what we want for most things but I specified black for the trip planner widget.
I need to look at which of 'body, select, input, textarea' makes this happen.

**Comment by jmfield2** [comment]
Sorry, here are the screenshots for the widget border and size issues:

Note how the trip planner has no border between the top bar and the widget title (first red box) on the full width desktop vs smaller resized screen.  The widget is also much taller and has less inner padding then the layers widget on the desktop size.

![107-1](https://cloud.githubusercontent.com/assets/3628509/12451064/2fea45f4-bf55-11e5-8c8f-10f9a48fc69f.png)

![107-2](https://cloud.githubusercontent.com/assets/3628509/12451062/2fe84c9a-bf55-11e5-972c-25009422ebf3.png)

The layers widget has no border in either desktop or resized window, and is not as tall as the trip planner on desktop (less white space at the bottom of the widget):

![107-3](https://cloud.githubusercontent.com/assets/3628509/12451063/2fe86540-bf55-11e5-84d4-f65abfd30a99.png)

![107-4](https://cloud.githubusercontent.com/assets/3628509/12451061/2fdb1624-bf55-11e5-89f9-55e6bd920b84.png)

So it seems like the the trip planner widget should have the same top spacing as it does in the smaller window, and the layers widget needs spacing in both cases.  I think we talked also about possibly making the trip planner widget shorter on desktop, but with more inner padding (between the actual input controls and the widget border) similar to the layers widget.

**Comment by barbeau** [comment]
I agree that the small spacing between the Trip planner widget and top USF bar on the smaller screens looks good - we should change to use this for all screen sizes for Trip planner and Layers widgets.

I also agree that we should increase the inner margins on the Trip planner widget to give it more breathing room, similar to how the inside of the Layers widget is spaced.  And we should remove the bottom white portion of the Trip Planner widget - let's open a new issue for these margin issues.

**Comment by jailby** [comment]
What about the shadow on the control button of the widgets? Did you discuss this during the last meeting?

**Comment by jailby** [comment]
By looking at the css I also notice [this block of code](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/style.css#L569).

I would like to delete it because it actually makes the info widget (e.g.: icon legend) bigger on smaller resolution.

Screenshot for my full screen window:
![image](https://cloud.githubusercontent.com/assets/1370401/12482762/6df11ca4-c01f-11e5-9c59-401a314508c7.png)

Screenshot with the window re-sized:
![image](https://cloud.githubusercontent.com/assets/1370401/12482746/53f0488e-c01f-11e5-81e6-f1d635f53156.png)

Result when deleted (on small window):
![image](https://cloud.githubusercontent.com/assets/1370401/12483003/a9775828-c020-11e5-832d-557be556ab2a.png)

**Comment by barbeau** [comment]
> I would like to delete it because it actually makes the info widget (e.g.: icon legend) bigger on smaller resolution.

Agreed, it shouldn't be that big.  

On a related note, the Help and Feedback widgets should appear on top of the Trip Planner and Layers widgets - right now they are behind them.

> What about the shadow on the control button of the widgets? Did you discuss this during the last meeting?

We didn't discuss this specifically, as far as I recall.

**Comment by jailby** [comment]
Ok, the control buttons are a problem. I will elaborate tomorrow during the meeting.

I quickly created another issue for the "on top" thing to not loose it in this big issue.

I'm still working on the border and everything for the trip planner and layer widget.
