### ISSUE TITLE
Save most recently viewed widget, show at startup

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#165]
If a student mainly uses the Layers widget, currently each time they use the site they have to go to the menu and switch from the Trip Planner (the universal default) to the Layers widget.

We should save the most recently used feature, either Layers or Trip Planner, and default to that view when the user opens the page.

@jailby could you please work on this?

**Comment by jailby** [comment]
I thought about this and to do so I need to add a cookie probably as follow:
`document.cookie = "widgetUsed=trip; ";`
So I have a question on where to place this. 

1) Should I add it to the [onClick tag of the button](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/index.html#L233)?

2) Or should I add it to the function that unminimize the widget?

I'm not sure what is a good practice for js/html. Also, the onClick tag has already 4  functions in it and I don't know if it would be over using it to add a fifth function in it.

**Comment by barbeau** [comment]
My feelings is that we should manage it onClick of the menu buttons, similarly to how we're managing switching of the widget focus.

**Comment by jmfield2** [comment]
Yes, something like what you have for widgetUsed=trip -- you'll also need to set the expires parameter (http://www.w3schools.com/js/js_cookies.asp) so that it persists after the browser is closed - probably like how we did for the welcome widget.

Adding the code to the unminimize might be more correct, but it would require more work (at least to determine which widget was unmimized, etc)..  Adding another call to onclick isn't a huge problem but you could perhaps create another function inside of <script></script> somewhere in global scope (index.html) and then call that if you want..

**Comment by jailby** [comment]
Ok I wanted to make sure it was ok to add this function to onClick.
