### ISSUE TITLE
Removing the minimized tab

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#167]
The trip planner and layers widgets can be minimized.
They then appear at the bottom left of the screen.

This somewhat obstruct the visibility of a part of the map. 

Also, these elements don't interact has wanted when clicked on it.
If the minimize tab is clicked the widget appear on top even if there was another widget present. This stacks the widgets and does not look good.

Removing this tab would not affect the fact that a user can reopen the widgets through the menu.
This is a trade off since the user would have to click twice to get back a "minimized" widget (once on the menu and then once more for the corresponding widget).

Note: Do not remove the tab for "itinerary returned".

**Comment by jmfield2** [comment]
Related to #120  - screenshot of one possible option to improve itinerary results on _mobile_ by minimizing the itinerary results window so the trip is initially visible on the map.

Another possibility is to revise the itinerary results (on mobile, again) to be small, floating boxes  (on the top left) with icons representing different app shortcuts: itinerary #, back to search, ... so that again the full trip is visible instead of being mostly obscured by a widget until it is minimized.

![screenshot from 2016-03-25 15 12 31](https://cloud.githubusercontent.com/assets/3628509/14129104/e1aed310-f5f4-11e5-887f-d186ad5fc743.png)
