### ISSUE TITLE
Map localization on mobile

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#168]
**Problem:** When opening the map, on mobile, the blue circle indicating the position of the user is hidden by the trip planner widget. The location of the map is not ideal even for the layer widget.
Screenshot of the problem:
# trip

![image](https://cloud.githubusercontent.com/assets/1370401/12859690/f87b52f6-cc25-11e5-8104-cf6c06724e13.png)
# layers

![image](https://cloud.githubusercontent.com/assets/1370401/12859701/00d5d3fe-cc26-11e5-80d9-af3b24bc7f2b.png)

**Solution:** For #layers and #trip move the map in order to make the blue circle directly visible.
Screenshot to show example of the solution:
![image](https://cloud.githubusercontent.com/assets/1370401/12859719/22e50e38-cc26-11e5-844a-978d3574780b.png)

**Note:** the map localization when opened with #map is fine. Don't change it.
Screenshot of it:
![image](https://cloud.githubusercontent.com/assets/1370401/12859728/2ff61e46-cc26-11e5-848a-487d76ad258b.png)

**Comment by barbeau** [comment]
+1 - When the Layers and Trip Planner widgets are used as the opening screen, we should position the screen so the user's real-time location is centered in the open space below, something like:

![image](https://cloud.githubusercontent.com/assets/928045/12860206/2531a388-cc29-11e5-86fe-d0692a100d7e.png)

**Comment by barbeau** [comment]
Mentioned in today's meeting, and related to handling real-time positioning - the current real-time positioning functionality is driving me crazy.  You constantly have to fight it by default, because when you pan the map yourself it will try to pan back to your real-time location.  And the button toggels map panning on/off, which isn't the behavior of any other major app/website that I'm aware of (in most apps tapping the button will always center on your position), and as a result isn't likely a behavior users will expect.

I'd like to remove the current leaflet control that's managing this, and just replace it with a simple button.  When you tap the button, it will pan the map and center on your location (with some offset if the Trip Planner widget is open, as mentioned above).  Otherwise, it doesn't do anything (i.e., no automatic panning of map).  I'd also like to change the icon to the normal crosshairs icon - https://materialdesignicons.com/icon/crosshairs-gps.

@jmfield2 will look at implementing this.
