### ISSUE TITLE
Blue light layer title cascades to next line

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#183]
@jmfield2 Looks like the Blue Light Phone layer title is cascading to the next line on mobile:

![image](https://cloud.githubusercontent.com/assets/928045/13052357/759d7a22-d3cc-11e5-9b7b-ab832c351b29.png)

Maybe we use "Blue Light Phones" instead?  Other ideas welcome.

**Comment by jailby** [comment]
We might want to make the widget larger.

We could have the checkbox in front of two line of text which would describe the entry (instead of coming back to a new line after the checkbox).

**Comment by barbeau** [comment]
I think I'd prefer to avoid making the box bigger horizontally - it's nice that it currently doesn't block much of the screen.

Allowing two lines of text, with the check box always being to the left of the first line might be a good solution.  So something like:

![image](https://cloud.githubusercontent.com/assets/928045/13053701/dd0b551a-d3d3-11e5-9a3b-9cb7bca01a0d.png)

**Comment by jailby** [comment]
I don't know what is the easiest in css but does the following also looks good?

![image](https://cloud.githubusercontent.com/assets/1370401/13053904/eef12b78-d3d4-11e5-9692-89169ded8a22.png)

**Comment by barbeau** [comment]
@jailby From some quick Googling that alignment might actually be more common.

I think the biggest question we need to answer is "do we need a 2nd line of text"?  There is definitely an advantage to forcing layer descriptions to be shorter.  Thoughts?

**Comment by jailby** [comment]
My thought was that the word "emergency" has a lot of weight here and I believe that removing this key word may hurt the understanding of some people. For a visitor, or few people, the blue light may not ring any bell.

I believe that the "blue light" are explained at orientation, thus we might be able to assume that most people know that these blue lights indicate an emergency phone.
I think "emergency phone" is more important, but "blue light" should be known by most people on USF campus.

I agree with the fact that we should be concise and we shouldn't have "a lot" of characters to describe a layer.

That was my thought process behind my previous comments.

**Comment by barbeau** [comment]
> My thought was that the word "emergency" has a lot of weight here and I believe that removing this key word may hurt the understanding of some people.

I agree with this.  Let's see if we can find a nice way to show "Blue Light Emergency Phones" in two lines.

**Comment by jmfield2** [comment]
I tried a couple of ways to accomplish this and I think the best way will be to convert the [box] label to use tables instead of the current floating elements..  Another way is to use relative/absolute position tricks but it the layout isn't as consistent as the table method.  There is also 'flexbox' css, but I didn't try that because so far tables I think might be the easiest way to do what we want:

![screenshot from 2016-02-16 09 00 53](https://cloud.githubusercontent.com/assets/3628509/13078542/c70b8dd8-d48d-11e5-801b-cce25cc16402.png)

The top two use two table rows, the bottom use rel/absolute positions -- note the bottom row is slightly off-center vertically compared to the top row.

**Comment by barbeau** [comment]
Tables look good to me.
