### ISSUE TITLE
 Bus Position Layer

### ISSUE THREAD

**Issue by TNWolf** [CUTR-at-USF/usf-mobullity#2]
Bus Position Layer not currently working because not sure how to get to my vehicle positions API.. (used to be otp-rest-servlet/ws/vehicle_positions as seen here http://mobullity.forest.usf.edu/otp-rest-servlet/ws/vehicle_positions)

**Comment by jmfield2** [comment]
This is from

https://github.com/CUTR-at-USF/usf-mobullity/blob/usf-GTFSrt/otp-core/src/main/java/org/opentripplanner/api/ws/VehiclePositionsList.java

right?

**Comment by TNWolf** [comment]
Yes. That is where the file was before the rebase.

**Comment by jmfield2** [comment]
The following patch appears to fix this issue.  I can commit it first if it's easier to test, but basically the issue seems to have just been missing the VehiclePositions.class in the standalone/OTPApplication.java (assuming you don't have it running in tomcat...if so, probably won't help), from there the otp.config.restService is defined as otp/routers/default/ which is fine for some other stuff, but not vehiclepositions (now just /otp/vehicle_positions)... perhaps we should change the path there instead of hard-coding it into BusPositionsLayers.js like I did.  Finally, changing showBusPositions to true in otp/config.js enables the bus layer and updates as expected as far as I can tell.

```
------------------------- src/client/js/otp/config.js -------------------------
index 5df465c..eec50e7 100644
@@ -74,7 +74,7 @@ otp.config = {
     metric              : false,
     showBullRunnerStops    : false,
     showHartBusStops   : false,
-    showBusPositions   : false,
+    showBusPositions   : true,


     /**

---------------- src/client/js/otp/layers/BusPositionsLayer.js ----------------
index a45318b..611d507 100644
@@ -86,7 +86,7 @@ otp.layers.BusPositionsLayer =

        liveMap : function() {
            this_ = this;
-           var url = otp.config.hostname + '/' +  otp.config.restService + "/vehicle_positions";
+           var url = otp.config.hostname + '/' + "otp/vehicle_positions";
            $.ajax(url, {
                type: 'GET',
                dataType: 'JSON',

------- src/main/java/org/opentripplanner/standalone/OTPApplication.java -------
index 5913c08..e6001b7 100644
@@ -24,6 +24,7 @@ import org.opentripplanner.api.resource.SimpleIsochrone;
 import org.opentripplanner.api.resource.SurfaceResource;
 import org.opentripplanner.api.resource.TileService;
 import org.opentripplanner.api.resource.TimeGridWs;
+import org.opentripplanner.api.resource.VehiclePositions;
 import org.opentripplanner.index.GeocoderResource;
 import org.opentripplanner.index.IndexAPI;
 import org.slf4j.bridge.SLF4JBridgeHandler;
@@ -96,8 +97,9 @@ public class OTPApplication extends Application {
             /* Features and Filters: extend Jersey, manipulate requests and responses. */
             AuthFilter.class,
             CorsFilter.class,
-            // Enforce roles annotations defined by JSR-250
-            RolesAllowedDynamicFeature.class
+            /* Enforce roles annotations defined by JSR-250 */
+            RolesAllowedDynamicFeature.class,
+            VehiclePositions.class
         );
     }
```

**Comment by TNWolf** [comment]
Issue fixed with that patch.
