### ISSUE TITLE
Add hybrid (satellite + building names) map tile provider

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#203]
From USF UCM:

> The building labels don’t appear on the satellite view. Is there the ability for a hybrid map, that shows the satellite view with the labels overlayed?

Looks like we might be able to add Google Map hybrid map tiles, although I'm not sure what the license is:
http://stackoverflow.com/questions/23017766/google-maps-tile-url-for-hybrid-maptype-tiles

We could also use Mapbox tiles, both for normal map and hybrid:
https://www.mapbox.com/developers/api/styles/

Their retina tiles look really good on high-res displays.

We'd need to see if the normal Mapbox tiles have OSM foot paths, though, and if we're losing anything else we currently have from MapQuest OSM map tiles.

I'll look at grabbing a Mapbox API key so we can test.

**Comment by barbeau** [comment]
See also this library for adding more tile providers:
https://github.com/leaflet-extras/leaflet-providers

Here's a demo:
http://leaflet-extras.github.io/leaflet-providers/preview/

**Comment by jmfield2** [comment]
Also, it looks like MapQuest offers hybrid maps when you specify 'hyb' in
the tile URL vs map and sat

**Comment by barbeau** [comment]
@jmfield2 Ah, nice find.  Let's use 'hyb' to address this issue, and we can move changing tile providers to a new issue.

**Comment by jmfield2** [comment]
I've added support for mapquest-style hybrid overlay tiles, and tested the various map options using mapbox.  Note that mapbox does not require the same tile layering that mapquest does (satellite + hybrid) in order to get hybrid maps.

I think the screenshots below illustrate the extent to which mapbox aesthetics beat mapquest in nearly every way.  The pure map style of mapbox does seem a little cartoonish, but in a good, artistic, and clean way.  OTOH, mapbox satellite details way exceed mapquest.  The mapbox hybrid labels are sometimes difficult to read (white on a light background). Though, I think mapbox would potentially give much greater control over those issues and more..

Also, mapbox doesn't include building and parking lot names or the blue P icons like mapquest (at least in this example).

Mapquest standard:
![screenshot from 2016-03-09 23 23 07](https://cloud.githubusercontent.com/assets/3628509/13659743/3a81306c-e652-11e5-9f4d-77a35ed8c2b6.png)

Mapbox standard: (mapbox.streets)
![screenshot from 2016-03-09 23 23 01](https://cloud.githubusercontent.com/assets/3628509/13659746/431d2834-e652-11e5-841d-6eda6dbfcbb8.png)

Mapquest satellite:
![screenshot from 2016-03-09 23 32 22](https://cloud.githubusercontent.com/assets/3628509/13659750/4f10bdb8-e652-11e5-91f0-f06f327e1b96.png)

Mapbox satellite: (mapbox.satellite)
![screenshot from 2016-03-09 23 32 14](https://cloud.githubusercontent.com/assets/3628509/13659749/48ad0580-e652-11e5-91a0-ea0db19a79e9.png)

Mapquest hybrid:
![screenshot from 2016-03-09 23 47 33](https://cloud.githubusercontent.com/assets/3628509/13659775/675ae402-e652-11e5-8814-ef3f61f410a2.png)

Mapbox hybrid: (mapbox.streets-satellite)
![screenshot from 2016-03-09 23 47 27](https://cloud.githubusercontent.com/assets/3628509/13659778/6d0f4b5e-e652-11e5-811f-6052d9e6f6f6.png)

**Comment by barbeau** [comment]
Thanks for trying this out @jmfield2.  Mapbox looks great - only downside I think would be losing some of the building name and abbreviations.  I think we may have some control over Mapbox styling of tiles - for example, see https://www.mapbox.com/blog/custom-styles-mapbox-streets/.  If we can style the building names so they always appear and are a bit more readable in the satellite view, I'd say we should definitely switch to Mapbox.

**Comment by barbeau** [comment]
Actually, I believe this is the updated link for Mapbox styles:
https://www.mapbox.com/help/customizing-map-colors/
