### ISSUE TITLE
Max walk and max bike field contents aren't validated

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#209]
From USF UCM:

> For “Maximum walk” and “maximum bike” fields, a user can enter non-numerical values, and no error is given. The use of “Presets” as the default drop down choice would be better served if users could only choose from the drop down, for example
> - Maximum walk: [drop down—default value 0.30] mi. 
> - If the decision is made to allow users to enter their own value, recommend to open the numerical menu only, and validate.

In our meeting today we agreed that's its probably best to eliminate the edit text field, and just keep the preset dropdown for both of these fields:

![image](https://cloud.githubusercontent.com/assets/928045/13542660/48128312-e232-11e5-9587-0bafb1d5222e.png)

We'd need to rename the preset dropdown to the selected value.

We should keep the current default values.

**Comment by jailby** [comment]
Here is a screenshot of the solution:
![image](https://cloud.githubusercontent.com/assets/1370401/14048605/b909b064-f285-11e5-971d-aecd4a2a3e2f.png)

A couple things I want to mention about this fix:
1) Since the text field is deleted the user doesn't know that there is a default value that is 0.30 miles.
2) To have "Presets:" as the 'title' of the selector by default it also makes "Preset:" one of the option is the dropdown list. This was an already present behavior but it is related to the suppression of the input field. 
2.a) I think its not really 'clean' to have "Presets:" as one of the element of the dropdown list.
2.b) In the previous version if the user select one preset (e.g. .75 mi.) the value will be transfered in the input field and if, after this selection, the user click back on the option "Presets:" the value in the input field will not change. Therefore the user know that the selected. In the fix the user doesn't know which value is selected anymore.

I have thought about some solutions that I will remember to discuss in this afternoon meeting.

**Comment by barbeau** [comment]
@jailby You can't automatically set the field to the 0.30 mile option?

**Comment by jailby** [comment]
I have to pause my progress so I'm writing it down.
I'm trying to set the selected value of the dropdownbox to the currentMaxDistance.

This line: `$('#'+this.id + '-presets').val(parseFloat(this.currentMaxDistance)+'0 '+this.distSuffix);` should do the work. However, it is not working at the moment.

I made a minimal example thanks to a fiddle:
https://jsfiddle.net/n96zbbwe/

If currentMaxDistance is not one of the option it will select automatically the first option.
So we can have a check as follow:
`$('#'+this.id + '-presets').val() == parseFloat(this.currentMaxDistance)`
`$('#'+this.id + '-presets').val()` return the value of the selected option
We need to parseFloat() because currentMaxDistance is under the form: `f.f distSuffix`

if this check is true do nothing otherwise we need to add an option that has the value of the currentMaxDistance and select it

**Comment by jmfield2** [comment]
I think I fixed the fiddle on /1/ - basically, the options need value= and
Val should use that not + distsuffix

**Comment by jailby** [comment]
The fiddle was working. Did it not work for you?

I realized that I didn't mention it but what is not working is the line `('#'+this.id + '-presets').val(parseFloat(this.currentMaxDistance)+'0 '+this.distSuffix);` in my local.

When options don't have a value then the text of the option are set as the value:
http://stackoverflow.com/questions/3644449/jquery-setting-select-list-selected-based-on-text-failing-strangely?answertab=active#tab-top

**Comment by jmfield2** [comment]
Sorry, yep this worked for me like it was...I didn't check closely enough
lol

Where were you trying to add this in the tripoptionswidget?  Maybe it is
just a context issue and using this_ might fix it..

**Comment by jailby** [comment]
That's what I was thinking might be the problem.

I tried multiple places.

The place that makes the most sense to me (because its after the layout) is here:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js#L686

I also tried here (because its at the end of initialization):
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js#L681

And I'm not entirely sure what the function change() is doing here:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/widgets/tripoptions/TripOptionsWidget.js#L687

That's another possible block of code that may interfere with what I'm trying to do.

**Comment by jailby** [comment]
So what I was doing was right but I didn't know about `toFixed(2)`, which solves the problem I had: http://www.w3schools.com/jsref/jsref_tofixed.asp

Thanks @jmfield2 for letting me know about this function.

Here is a screenshot of the dropdown list already set to the default max distance:
![image](https://cloud.githubusercontent.com/assets/1370401/14211257/019a4da0-f7fb-11e5-97f1-227f75c383e7.png)

**Comment by barbeau** [comment]
:+1: Looks good!
