### ISSUE TITLE
Bikeshare icon in itinerary summary is hard to see

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#242]
If you plan a bikeshare trip, it's very difficult to see the icon in the itinerary results (blue section below):

![image](https://cloud.githubusercontent.com/assets/928045/14083107/ee721bb6-f4e1-11e5-9f22-5ca20e3e6bb9.png)

Above screenshot is zoom in a bit from normal desktop size - when it's smaller it's even more difficult to see.

We should implement a better contrasting icon/background color combination.

**Comment by barbeau** [comment]
Here's a link that reproduces this on mobullity.forest:
http://mobullity.forest.usf.edu/?module=planner&fromPlace=28.06701965496018%2C-82.40690231323241&toPlace=28.058082339261862%2C-82.41926193237305&time=2%3A25pm&date=03-28-2016&mode=BICYCLE_RENT&maxWalkDistance=482.8032&wheelchair=false&arriveBy=false&showIntermediateStops=true&itinIndex=0

**Comment by jmfield2** [comment]
The problem seems to be here:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/modules/planner/ItinerariesWidget.js#L297

I guess it is trying to match the 'mode color' used elsewhere in the trip planner or itinerary ... so, we can either change that color in all places for bike legs, or change the color or style of the middle from blue to gray like the outside..

The icon is a PNG, but it might also be possible to change the black to white.

**Comment by jmfield2** [comment]
![screenshot from 2016-04-29 00 23 01](https://cloud.githubusercontent.com/assets/3628509/14908126/abbd89e0-0da0-11e6-80bd-103e4e8f0001.png)

By inverting colors of the icon image.
