### ISSUE TITLE
Geolocation is broken on Chrome - requires HTTPS

### ISSUE THREAD

**Issue by jailby** [CUTR-at-USF/usf-mobullity#263]
The following error message is displayed in the console:

![image](https://cloud.githubusercontent.com/assets/1370401/14790486/85bc9ec0-0adf-11e6-9cb6-89b55d94c12a.png)

text:
getCurrentPosition() and watchPosition() are deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

The getCurrentPosition() function is used once at line 4 of src/client/js/otp/config.js and the watchPosition() function is not used.

**Comment by jmfield2** [comment]
This should be fixed if we enable HTTPS - I don't know if it's possible to
do anything else .. Removing them would break the GPS function

We should check how easy it is to serve HTTPS via standalone Java app, then
also ping IT when ready so the load balancer etc will work too

**Comment by jmfield2** [comment]
To answer the question of when this is being deprecated - the answer was posted on HN today:

Chrome: 4/20/16 https://developers.google.com/web/updates/2016/04/geolocation-on-secure-contexts-only
(Confirm that geolocation is now broken on my mobile chrome)

Firefox: Doesn't appear to have a hard date, but discussed at: https://bugzilla.mozilla.org/show_bug.cgi?id=1072859

**Comment by barbeau** [comment]
Yikes - so we need to fix this ASAP.  I changed the milestone to USF UCM, as we'd need to fix this prior to soft launch.

**Comment by barbeau** [comment]
Confirmed on desktop too - on my machine with Chrome `Version 50.0.2661.94 m`, geolocation is broken.

**Comment by cagryInside** [comment]
Found this one: http://grizzly.1045725.n5.nabble.com/How-to-redirect-HTTP-to-HTTPS-td5710368.html

**Comment by barbeau** [comment]
Looks like there is a `HttpRedirectFilter` in Grizzly:
https://grizzly.java.net/docs/2.2/apidocs/org/glassfish/grizzly/config/portunif/HttpRedirectFilter.html

**Comment by jmfield2** [comment]
Using cagry's suggestion I was able to implement a separate HttpServer for the insecure port which just redirects all connections to the secure port (via Location: header and 301 HTTP Status).  

This seems to work so far, the only potential issues being there are now two separate Grizzly HttpServer's running (one for 80, one for 443), and how should we configure the target domain to redirect to?  I was thinking we could hard-code or configure maps.usf.edu and mobullity.forest.usf.edu and select one based on the incoming host http parameter.  The only other host we might want to handle (for development) is localhost, but that isn't strictly necessary.

Other requests to this port should either not be handled or use a reasonable default to prevent an open/untrusted redirection vulnerability since the Host parameter is provided by the client.

**Comment by barbeau** [comment]
> I was thinking we could hard-code or configure maps.usf.edu and mobullity.forest.usf.edu and select one based on the incoming host http parameter. 

That makes sense to me.

**Comment by barbeau** [comment]
@jmfield2 I believe this issue should now be fixed after merging https://github.com/CUTR-at-USF/usf-mobullity/pull/276?

If so please feel free to close.

**Comment by jmfield2** [comment]
fixed by a534afe
