### ISSUE TITLE
Some widgets aren't centered in MyUSF Android

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#293]
In MyUSF Android app, you can now access this site by tapping on "Tampa Maps (beta)".

However, the first time you do this the splash screen isn't centered and hides part of the screen:

![image](https://cloud.githubusercontent.com/assets/928045/16591356/95e2140e-42a9-11e6-8f08-6883801b09f7.png)

When returning to the site a second time via the MyUSF link, everything looks ok as the splash screen doesn't appear.

I’m seeing something similar when doing “Menu->Help” and “Menu->Send feedback”.

We should fix this to center correctly, if possible, or look at removing/altering it if not.

**Comment by barbeau** [comment]
Looks like this doesn't happen on MyUSF iOS:

![image](https://cloud.githubusercontent.com/assets/928045/16591923/3ca33258-42ac-11e6-868e-df77493e1877.png)

I've asked USF IT to ask their MyUSF vendor about this - in the mean-time, we can see if there are any workarounds for Android.

**Comment by jmfield2** [comment]
I'll look more at the APK for clues, but the widgets themselves are centered @ src/client/js/otp/widgets/Widget.js:220  calculating the $(window) (probably set via a viewport setting or something similar) width/height - the width/height of the widget.

I imagine it might be related to either the window setting not be properly filled because of some other invalid setting, or being called before it is available.

One workaround - if that is the culprit - might be to set the window/widget size or widget position values to some reasonable default if it doesn't seem correct (it looks like it is stuck @ the top, below the myusf header?)

**Comment by jmfield2** [comment]
This is caused because from the app, the window height is not available so the widgets receive a "top" position of -65px.  (0 - widget height/2)

The reason is partially webview and probably mostly our issue, in my opinion, because we initialize the OTP webapp with an inlined JS code block and rely on the jquery document ready callback to fire at an appropriate time.  We have not noticed any issue on desktops/fast computers, but it could definitely happen outside of webview.

Adding "defer" to the code block, and using $(window).load instead looks to fix this problem in my testing.  I'll PR that soon.
