### ISSUE TITLE
Analytics for MyUSF use vs. standalone use

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#296]
We should confirm that in Google Analytics we can tell when the site was accessed from MyUSF apps (and iPhone vs. Android), versus direct access through a web browser.  If we don't currently log this, we should add this as a feature.

**Comment by jmfield2** [comment]
Initially I thought we could not tell the difference since both actions are essentially the same.  Analytics does not appear to save the user agent as far as i can tell at this point, but in local testing of the myusf APK, I see that it is sending the following user agent:

```
User-Agent: Mozilla/5.0 (Linux; Android 6.0.1; Nexus 6 Build/MMB29X; wv) AppleWebKit/537.36
(KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.81 Mobile Safari/537.36 
KurogoVersion/2.2.3 (Kurogo Android) KurogoOSVersion/6.0.1 KurogoAppVersion/8.2 
(com.pyxismobile.iUSF2.ui.activity.test)
```

So, it should be possible to track this.

One way is to use Google Tag Manager, or the Analytics SDK to save the UA string as a separate custom field that would be available in the reports like the standard "Browser" field.

iOS at least is tracking "Safari (in-app)" in google analytics, which seems to be what we want.
