### ISSUE TITLE
Electric car charging stations not included on our Layers

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#334]
In the "Layers" view, if you turn on the layer for electric car charging stations, click on the marker, and then click on "Charge Point' in the marker popup, it takes you to the Chargepoint website.

Their website shows several additional car charging stations near USF that we don't currently have mapped:

![image](https://cloud.githubusercontent.com/assets/928045/18274687/adeeea10-7411-11e6-8476-e5dd139a25f6.png)

We should confirm that these exist, and if so add them to our electric car charging layer.

**Comment by jmfield2** [comment]
Here is the output of the chargepoint API endpoint for the USF area as shown above:
- [x] USF BEARD GARAGE 01, 3800 USF Beard Drive; Beard Parking Garage, Level 1. Northwest Corner. Resident Permit Required.; ports=2, status=available; 28.0589630613,-82.417354011
- [x] USF BEARD GARAGE 02, 3800 USF Beard Drive; Beard Parking Garage, Level 1. Northwest Corner. Resident Permit Required.; ports=2, status=available; 28.0589405753,-82.4173566932
- [x] USF EVSE 02, 4202 E Fowler Ave; USF Cedar Cir. Parking Lot 5A, west side near lot entrance.; ports=2, status=available; 28.06407547,-82.4124298096
- [x] USF EVSE 01, 4202 E Fowler Ave; USF Cedar Cir. Parking Lot 5A, west side near lot entrance.; ports=2, status=available; 28.064125061,-82.412437439
- [x] USF PATEL CGS, 11810 USF Alumni Drive; Patel CGS Parking lot; ports=1, status=available; 28.055816784,-82.4082331508
- [x] FL DOT 7 HEADQUARTERS 01, 11201 N Malcolm McKinley Dr; South side of building adjacent carpool parking area; ports=2, status=available; 28.050153622,-82.4144882958
- [x] City of Temple Terrace, 11302 N 56th St; 24 hours daily; ports=4, status=unknown_dc; 28.0509643555,-82.3941268921
- [x] PALM LAKE JAEB CENTER 01, 15310 Amberly Dr; Side of building facing BB Downs, last space on right. 2hr max charging 8a -5p M-F. 4hr max charging all other times.; ports=1, status=available; 28.0916900483,-82.4035159398
- [x] Ferman Nissan of North Tampa, 11001 N Florida Ave; Dealership business hours; ports=1, status=unknown; 28.0496387482,-82.4583206177

It looks like all of those stations are managed by Chargepoint, and "verified".  Only the temple terrace and ferman nissan stations are "gray" on the map, the others are green.  Further, Ferman nissan is listed as a station on Google Maps, FWIW.

I think it is safe to add these to the map, but we should probably adjust the description since the current notice about USF permits doesn't apply to non-USF stations.  Perhaps we can just use some of the data from the API above? (# ports, name, address, description)

(from https://mc.chargepoint.com/map-prod/get?{%22station_list%22:{%22ne_lat%22:28.104139094925603,%22ne_lon%22:-82.30244566635741,%22sw_lat%22:28.013247891502637,%22sw_lon%22:-82.52526213364257,%22page_size%22:100,%22page_offset%22:%22%22,%22sort_by%22:%22distance%22,%22screen_width%22:1346,%22screen_height%22:658,%22filter%22:{%22connector_l1%22:false,%22connector_l2%22:false,%22is_bmw_dc_program%22:false,%22is_nctc_program%22:false,%22connector_chademo%22:false,%22connector_combo%22:false,%22connector_tesla%22:false,%22price_free%22:false,%22status_available%22:false,%22network_chargepoint%22:false,%22network_blink%22:false,%22network_semacharge%22:false,%22network_evgo%22:false,%22connector_l2_nema_1450%22:false,%22connector_l2_tesla%22:false},%22reference_lat%22:28.0587031,%22reference_lon%22:-82.41385389999999,%22include_map_bound%22:true},%22user_id%22:0})

Also note that USF (http://www.usf.edu/administrative-services/parking/parking/ev-charging-stations.aspx) only lists the 2 locations that we have listed, although chargepoint lists at least the 1 other (Patel).  If we include those, perhaps we should see if that list should be updated as well?

Also, note the site that Mohan found which might be useful for adding more EV-related functionality: http://openchargemap.org/site

Added in https://www.openstreetmap.org/changeset/42363911, and PR with some supporting changes coming shortly

**Comment by jmfield2** [comment]
Palm Lake station added in http://www.openstreetmap.org/changeset/42468890
