### ISSUE TITLE
Rendering layers with many markers

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#372]
With the addition of the collapsible layers and new groups (specifically on-campus living), we need to figure out a way to balance the size of the graph and the number of markers displayed at any given time.  

Currently, as a temporary workaround, we only build the points near the tampa campus into the graph so that no other markers are available.  https://github.com/CUTR-at-USF/usf-mobullity/commit/f5dbf313fb888de7f93d319a076e19d0c43f4da9

One solution to the issue is to add a bounding box parameter to the frontend endpoint and restrict the results returned to that area.

If we go with that, and the user pans the map (to see other areas), do we automatically refresh the layer and load markers for that area - clearing markers no longer in the area - or something else?

It seems like google maps doesn't update anything automatically (on mobile at least) - when the map is panned, it adds a button called "Search this area" which clears the previous markers and then finds new markers.

**Comment by barbeau** [comment]
In the OBA native apps we started with the strategy for bus stops to just clear the map and re-add the markers when the map is panned.  This is a little disconcerting from a UI perspective, and on Android creating flickering.  We changed to using a `HashMap` to track which bus stops had already been added to the map (up to a limit of 200), and if the stop wasn't added add a new marker.  Existing markers are kept until we exceed 200 markers, and then we clear the map and HashMap and start over.

I'd suggest the HashMap approach for the USF markers.  Its a small enough area that I think clearing and re-loading the markers on each map pan creates confusion, because you can have markers appearing and disppearing at the edges of the map boundaries, or when the user zooms in or out (which I imagine will happen a lot in the USF area.

**Comment by jmfield2** [comment]
OK - So, when the user pans the map, it will search the new area for markers and add them.  We should keep track of up to 200~ markers per layer (or the entire map/widget?) and only clear them when this is exceeded.  Should we just clear all of them at 200, only clear the oldest, or clear those that are not found in the new set?

That sounds fine to me.

There are also some leaflet plugins that do clustering automatically that I can check into as an alternative, too. (https://github.com/Leaflet/Leaflet.markercluster)

**Comment by barbeau** [comment]
> We should keep track of up to 200~ markers per layer (or the entire map/widget?)

We'd probably need to do some rough benchmarking of performance on mobile.  I picked 200 after doing some tests on lower-end Android devices.  I'm guessing that 200 total is probably  good upper limit.  Note that this means some markers might not be rendered at a particular zoom level if there are more than 200 within the bounding box - I think this is ok, and users can zoom in to find more.

> Should we just clear all of them at 200, only clear the oldest, or clear those that are not found in the new set?

On OBA Android we clear all and start over, as it's the easiest operation in real-time.  But, if we do the above we should benchmark on actual devices.

> There are also some leaflet plugins that do clustering automatically that I can check into as an alternative, too. (https://github.com/Leaflet/Leaflet.markercluster)

Yes, we should check this out.  Clustering is really the ideal solution, although again I'd want to do rough benchmarks on mobile.
