### ISSUE TITLE
Geolocation broken on Chrome for CUTR wired desktop

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#385]
**Summary:** 

No matter how long I wait, on my wired desktop at CUTR I never get a real-time location on the map using Chrome.  I've tried clearing the location permissions and restarting, and opening the site in incognito mode, same problem.

On the same machine Firefox geolocation works.  

On same machine maps.google.com gelocation works on Chrome.

On mobile and on my laptop connected to USF `eduroam` SSID it works without a problem on Chrome.

I'm guessing this is somehow related to the IP-based geolocation method that Chrome uses as related to the USF wired network.

**Steps to reproduce:** 

Go to maps.usf.edu or mobullity.usf.edu on my CUTR hard wired machine

**Expected behavior:** 

See the blue dot for my real-time location

**Observed behavior:** 

My real-time location never appears

**Platform:** 

My CUTR hard-wired machine, Windows 7 Enterprise SP1 w/ Chrome Version 54.0.2840.99 m (64-bit).  I have a static IP address.

**Comment by barbeau** [comment]
Opening the developer console in Chrome, I do see this:

~~~
leaflet.js:6 Uncaught TypeError: Cannot read property 'call' of undefined(…)
    fireEvent @ leaflet.js:6
    _handleGeolocationError @ leaflet.js:9
    (anonymous function) @ leaflet.js:6
~~~

**Comment by barbeau** [comment]
Looks like this is the issue:
https://github.com/Leaflet/Leaflet.draw/issues/555

**Comment by jmfield2** [comment]
It could be related to that leaflet issue, or to the issue JB referenced
last week which I believe was caused by an old and unused callback
reference from the locate widget .. seems strange that it works on wifi but
not wired, though.

Do you see the same error in the console in both cases, or just when it
doesn't work on wired?

**Comment by barbeau** [comment]
>Do you see the same error in the console in both cases, or just when it
doesn't work on wired?

Good question, I was just testing that :).

Looks like I see the same error in console when geolocation still works on USF WiFi in Chrome, so that Leaflet issue may not be related.

**Comment by jmfield2** [comment]
I started investigating this assuming it was an issue with IE, but of course it is with Chrome.  Using the local CUTR machine that I use (wired), I'm able to get a location marker on chrome, but not IE11.

IF this is related to the IP geolocation stuff, it is caused by:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/core/Map.js#L274

Which prevents the marker from being shown at an accuracy > 22K ...  For me, Chrome reports 702, and IE11 reports 34K.  Perhaps the IP I use is within Google's database and yours is not?  Can you test with IE11 and see if the geolocation works, too?

I think the PR just merged into mobullity tonight may help, and I am also going to submit a couple of other small fixes that should help the IP-geolocation issue on IE.. If you want to check the accuracy of the location you're getting you can set a breakpoint within that function in js/otp/core/Map.js and in the debugger print e.accuracy

**Comment by barbeau** [comment]
After some troubleshooting with @jmfield2 today, we started getting a `www.googleapis.com 400 error`.  We restarted my machine and it started working.  So, from this:
https://developers.google.com/maps/documentation/geolocation/intro#errors

... looks like either my Chrome instance didn't refresh it's geolocation API key, or somehow the requests were getting corrupted.
