### ISSUE TITLE
Only show the Welcome popup on the user's first visit to the app

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#41]
Related to https://github.com/CUTR-at-USF/usf-mobullity/issues/35, but I figured I'd pull this out in its own issue, since its a little different.

We're currently showing the "Welcome" popup on each visit to the site (see below).  This gets annoying fast.  We should only show this on the user's first visit to the site.

![image](https://cloud.githubusercontent.com/assets/928045/9137667/3ea014f6-3ced-11e5-8d5f-3ee2121087a6.png)

**Comment by jmfield2** [comment]
Looks like this is a consequence of other cookies (namely, google analytics it looks like) interfering with the original cookie for the welcome widget.

The getCookie and checkCookie functions inside of src/client/js/otp/modules/planner/PlannerModule.js 

need to be changed to conform to the key=value structure of document.cookie and then iterate the available cookies (perhaps a better way than simply String.split(';') if possible), instead of naively returning the first token, which is actually a keyname and not the expected 'true'

**Comment by barbeau** [comment]
Thanks @jailby!

**Comment by jailby** [comment]
The popup reappear if the user clear his/her cache.
Find a better way.

**Comment by jailby** [comment]
I added an expiration date and it should fix the problem.

Cookies are automatically deleted when the browser is close. However, when there is an expiration date the cookie will not be deleted until this date.

I set the date to "Fri, 13 Dec 2041 12:00:00 UTC". @barbeau is this date ok?

**Comment by barbeau** [comment]
@jailby 2041 date seems fine to me.
