### ISSUE TITLE
Default to Trip Planner view

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#44]
Based on feedback from USF, we should default to the trip planner view.  Currently we default to the Layers view.

**Comment by jailby** [comment]
When doing this the welcome popup need to updated to reflect this change:
![image](https://cloud.githubusercontent.com/assets/1370401/9495843/7a59ad66-4bdb-11e5-99ef-cd5db9984f8e.png)

The line to modify are line 145 to 147 in the following file:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/modules/planner/PlannerModule.js

**Comment by jailby** [comment]
I found the following commit where the layer tab has been set up has default:
https://github.com/CUTR-at-USF/usf-mobullity/commit/e5b1671ed96502d790ee92344a216b6da86cdb98

I'm pretty sure it is somewhere in this commit due to the change made on PlannerModule.js.
It's probably just an attribute to change but I haven't found it yet.

**Comment by jmfield2** [comment]
Looks like its at line 104? Of multimodal module
Where this.optionsWidget.minimize
Minimizes the trip planner

Maybe start layers as minimized instead

Also note that there's another issue requesting the ability to open a
particular window based on the url like
/#layers for the layers first
Or /#trip
Or /#map for nothing?

You can get this with:
Window.location.hash

**Comment by jailby** [comment]
I didn't found the other issue that you are talking about. @jmfield2 can you give me a link to it please.

I just finished, and I tested it a couple time and it seem to work. I need to test more, then I will commit and PR.

**Comment by jmfield2** [comment]
Lol it was mentioned in #35

**Comment by jailby** [comment]
@barbeau what should be the new start up popup?

Since the trip planner is the default widget open now, I can revert to the [previous statements of the popup](https://github.com/CUTR-at-USF/usf-mobullity/commit/e5b1671ed96502d790ee92344a216b6da86cdb98#diff-f3710d03c9d902ab8ece2396163c891fL136)

The only thing is that if a user use one of the "#widget" for example "#layers", then the popup statement will not correspond to the view of the user. We can also consider that a user that use "#layers" is an experienced user and therefore already visited the website, thus this user will not see the popup.

**Comment by barbeau** [comment]
@jailby That's fine - this will change anyway when we move to the hamburger menu, at which point we can just say something generic like "use the menu to change between the trip planner and layers".
