### ISSUE TITLE
When using itinerary link, center map on trip plan

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#45]
Currently, when using a link for a trip:
http://mobullity.forest.usf.edu/index.html?module=planner&fromPlace=28.05456022682711%2C-82.41329669952393&toPlace=CUT%3A%3A28.058091807150525%2C-82.41654753684998&time=9%3A19am&date=08-12-2015&mode=CAR

...the map centers on the user's location:

![image](https://cloud.githubusercontent.com/assets/928045/9225061/ffca9698-40d4-11e5-8596-24d66a5af370.png)

We should center of the results of the trip plan instead:

![image](https://cloud.githubusercontent.com/assets/928045/9225096/2ebae80e-40d5-11e5-808a-ed6726552f5d.png)

**Comment by jmfield2** [comment]
It also looks like this route is ignoring the gate barrier that is shown by
google and is apparently present in OSM - the way may need to be split.

**Comment by barbeau** [comment]
Good observation @jmfield2.  @jailby, could you please checkout the above?

**Comment by barbeau** [comment]
There is even worse behavior for this issue on Firefox when we don't have the user's location - you get a super-zoomed out view of west Florida, with the trip plan as a small dot on the map:

![image](https://cloud.githubusercontent.com/assets/928045/9253902/90f37a16-41ae-11e5-9d1d-c4ba1431dcbf.png)

**Comment by jailby** [comment]
Should we also include in the welcome popup that to have full access of the functionality of the website they should share their location?

This might need a separate issue:
The super-zoomed out view of West Florida also happen without planning a trip in Firefox if the user location is not available.
@barbeau let me know if I should create another issue

**Comment by barbeau** [comment]
@jailby I agree - if we don't have an issue that specifically covers default zoom when the user doesn't share their location (even if they don't plan a trip), please create a new issue, and link it to this one via the URL in the summary.  I think the default behavior should be if the user doesn't share their location with the app, the app should center on USF Tampa campus.

**Comment by jailby** [comment]
The following is the attribute that need to be set to true to solve this problem:
https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/config.js#L77

If this attribute is set to true the map will be center on the trip planned, when the user doesn't share his location. However, if the user share his location after the map is centered on the trip it will cause the map to center on the user location.
This functionality is wanted since the user does an action that generate this behavior.

The fix is on the way.

**Comment by jailby** [comment]
Coming back on my previous comment if the location is automatically shared, then the "zoom-in" on the user location will automatically happen **after** the view is "zoomed-in" on the trip. This interaction is not the best.

The solution could be to zoom on the trip as the last thing to do. If the user actually want to go to his/her location the "My location" button #70 should be pressed/clicked.

To fix this problem the code doing the zoom on the trip should appear after the code doing the zoom on the user's location.

**Comment by jailby** [comment]
I think I located [the code that change the map view  on the user location](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/core/Map.js#L151) after the view was centered on a trip.

However, I did not found the code center the view on a trip. I'm still looking for it and thinking of a solution for not calling queueView() when a trip is planned. @jmfield2 if you have any ideas don't hesitate to let me know.
I think the if statement right above is suppose to do that but obviously it is not working.

**Comment by jailby** [comment]
@jmfield2 When we discuss this problem I thought that you told me that leaflet was the cause of this problem. Leaflet actually do the map view position on the user location.

I'm not sure if it is exactly what you say or I misunderstood or something. However, I found that commenting [this line](https://github.com/CUTR-at-USF/usf-mobullity/blob/mobullityrebase/src/client/js/otp/core/Map.js#L151) fix the problem.

I believe that not making the call of this line when a trip is planned would fix the problem. Just commenting fix the problem but the map is never centered on the user's location anymore.

Since you said that you have refactored the function let me know when you PR like that I will pull right after.
