### ISSUE TITLE
Add white border line around real-time Bull Runner markers

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#48]
I've gotten feedback from a few people that the markers are difficult to see when they are on top of the route, because they are the same color.  This is especially true when viewing a few routes at a time.  I think adding a white outline may be enough to better distinguish them from the line.

For example of overlap, see below:

![image](https://cloud.githubusercontent.com/assets/928045/9231972/20ee1b28-40f9-11e5-931d-c3f77fb9de14.png)

Other suggestions are also welcome.

**Comment by jmfield2** [comment]
I did some work on refactoring the bus positions layer and the SVG markers to include a white border:

![screenshot from 2016-01-22 12 36 36](https://cloud.githubusercontent.com/assets/3628509/12518257/7f10e9c4-c105-11e5-9ab1-4ca4c47d755e.png)

I think the arrows also need the white border, but otherwise does this seem like an improvement?

I changed the style of the marker itself to simplify the svg code -- but I think it is very close to what it was.

Perhaps we should model our icons to be more like the usfbullrunner icons - like this?

![screenshot from 2016-01-22 12 43 36](https://cloud.githubusercontent.com/assets/3628509/12518313/ed897740-c105-11e5-9b0a-ced82ae3f73d.png)

`(http://usfbullrunner.com/images/vehicle_icons/w_1.gif)`

**Comment by barbeau** [comment]
Cool!  I think this is an improvement - I agree that adding a white outline to the arrow would be good too.  I would suggest sizing them the same as the new bike share icons (which I really like, BTW).

> Perhaps we should model our icons to be more like the usfbullrunner icons 

That's a good question.  I think I'd like to have more consistent iconography on our site, rather than just copying the others.  This will be helpful as we start adding more layers too.  So, with the bikeshare icons being more marker-shaped, I would say we should keep the Bull Runner icons the same shape.

But I'm open to it being different if you both have a strong opinion otherwise.

**Comment by jmfield2** [comment]
Should be fixed by 7dd889c
