### ISSUE TITLE
Metadata Map Boundaries

### ISSUE THREAD

**Issue by jmfield2** [CUTR-at-USF/usf-mobullity#71]
Currently the /otp/routers/default/metadata API is giving lower left and upper right boundaries for mobullity as the entire greater tampa area.

This appears to be caused by the HART GTFS data that is built into the graph - they add enough temporary edges to expand the map boundaries even though the rest of the network is not available.

Should we build the full graph for tampa instead of just the usf area on mobullity?  Perhaps it will be OK if the larger graph is only used for production and not on development?

**Comment by barbeau** [comment]
Yes, we should include the full graph for Tampa, definitely HART data, and probably PSTA in Pinellas County as well (if performance is an issue PSTA could be dropped).  Is the main downside of including the larger graph in development slower development time?

IMHO, I think we should try to keep the development and production environments consistent, so any possible issues appear in development first.

**Comment by jmfield2** [comment]
In local dev it makes a significant difference in loading time, but the
actual mobullity servers probably should use the same since they don't need
to start and stop very often.

The sizes - 300mb for uncompressed osm data and 100mb serialized - might
eventually be an issue being stored in chef, but I think it will be OK for
now

They use amazon s3 but don't report any quotas - other users have said they
will notify you if you start using way too much which I'm guessing should
be in the GB or more range.

Is there a live link with psta gtfs data like hart?

**Comment by barbeau** [comment]
Ok, I'll leave it up to you and @jailby how you want to manage the development environment - I understand that it doesn't make sense to spend development time staring at the screen if not necessary, and if removing the data enables that, it makes sense to me.

Official PSTA GTFS data is here:
http://www.psta.net/latest/google_transit.zip

Also FYI, the site GTFS Data Exchange is set up to auto-archive most of the publicly shared GTFS datasets in the known world:
http://www.gtfs-data-exchange.com/agency/psta/

So that's a good place to look for both official URLs, as well as past archived datasets, for any agency.  I hadn't previously though about it, but we could post our USF Bull Runner data there as well.  I'll look at setting that up.

**Comment by barbeau** [comment]
Ok, I just added the USF Bull Runner to hte GTFS Data Exchange with the download link:
https://github.com/CUTR-at-USF/bullrunner-gtfs-realtime-generator/raw/master/bullrunner-gtfs.zip

...although it doesn't publicly appear yet.  So, we'll just need to make sure we keep the filename consistent.

**Comment by jmfield2** [comment]
The graph is now updated to a recent tampa extract from mapzen and includes the remote URLs for HART, PSTA, and HART in chef.

Note: It takes about 1-2 minutes to start OTP using this graph on the VPS during which time java is pegged @ 99% CPU.  Once it is loaded, the process is using about 900MB of ram.
