### ISSUE TITLE
USF PATS request - reduce square "P" for parking symbols

### ISSUE THREAD

**Issue by barbeau** [CUTR-at-USF/usf-mobullity#99]
This is from USF PATS, but a lower priority issue.

On our map tiles, in a few places there are a large number of blue "P" parking symbols for the same lot.  For example, see Lot 1, and Lot 2A, and Lot 36 below:

![image](https://cloud.githubusercontent.com/assets/928045/10619697/115983b4-7745-11e5-9ca5-6d6c2c98c851.png)

USF PATS wants to reduce this to one "P" per larger lot.  I assume the multiple "P"s are triggered when there are breaks in the lots and OSM renders them as individual lots, each getting a "P".

One way to fix this is to render our own tiles, but I think that's too much effort at this point, and overkill for this one feature (although we may want to eventually render our own tiles for a more comprehensive re-design of the tiles).

A workaround may be to edit the OSM data to get the lots to somehow render logically as one lot.  We'll likely need to dig into the OSM data to figure this out.

I'm labeling this as "V2" milestone because its lower priority.

**Comment by jailby** [comment]
Some of these (additional) "P" are trigger because there are retrieved from OSM.
Some OSM's contributor created separate parking lot for disable (for example, not only) area within a parking lot.

This is not the right way to do it anymore:
http://wiki.openstreetmap.org/wiki/Proposed_features/parking

OSM should be updated with the tag parking_space which allow contributor to specify tag such as disable for some specific space within a parking lot.
Parking space tag utilization:
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking_space

A quick fix would be to not render the disable parking but some parking would be left out. For example the lot in the loop by ENB and lot 8C.

Another fix could be, instead of rendering a "P" for disable parking lot, a disable parking icon could be rendered.

**Comment by jailby** [comment]
Some of these (additional) "P" are trigger because there are retrieved from OSM.
Some OSM's contributor created separate parking lot for disable (for example, not only) area within a parking lot.

This is not the right way to do it anymore:
http://wiki.openstreetmap.org/wiki/Proposed_features/parking

OSM should be updated with the tag parking_space which allow contributor to specify tag such as disable for some specific space within a parking lot.
Parking space tag utilization:
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking_space

A quick fix would be to not render the disable parking but some parking would be left out. For example the lot in the loop by ENB and lot 8C.

Another fix could be, instead of rendering a "P" for disable parking lot, a disable parking icon could be rendered.

**Comment by jailby** [comment]
Some of these (additional) "P" are trigger because there are retrieved from OSM.
Some OSM's contributor created separate parking lot for disable (for example, not only) area within a parking lot.

This is not the right way to do it anymore:
http://wiki.openstreetmap.org/wiki/Proposed_features/parking

OSM should be updated with the tag parking_space which allow contributor to specify tag such as disable for some specific space within a parking lot.
Parking space tag utilization:
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking_space

A quick fix would be to not render the disable parking but some parking would be left out. For example the lot in the loop by ENB and lot 8C.

Another fix could be, instead of rendering a "P" for disable parking lot, a disable parking icon could be rendered.

**Comment by jailby** [comment]
Some of these (additional) "P" are trigger because there are retrieved from OSM.
Some OSM's contributor created separate parking lot for disable (for example, not only) area within a parking lot.

This is not the right way to do it anymore:
http://wiki.openstreetmap.org/wiki/Proposed_features/parking

OSM should be updated with the tag parking_space which allow contributor to specify tag such as disable for some specific space within a parking lot.
Parking space tag utilization:
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking_space

A quick fix would be to not render the disable parking but some parking would be left out. For example the lot in the loop by ENB and lot 8C.

Another fix could be, instead of rendering a "P" for disable parking lot, a disable parking icon could be rendered.

**Comment by jailby** [comment]
Some of these (additional) "P" are trigger because there are retrieved from OSM.
Some OSM's contributor created separate parking lot for disable (for example, not only) area within a parking lot.

This is not the right way to do it anymore:
http://wiki.openstreetmap.org/wiki/Proposed_features/parking

OSM should be updated with the tag parking_space which allow contributor to specify tag such as disable for some specific space within a parking lot.
Parking space tag utilization:
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking_space

A quick fix would be to not render the disable parking but some parking would be left out. For example the lot in the loop by ENB and lot 8C.

Another fix could be, instead of rendering a "P" for disable parking lot, a disable parking icon could be rendered.

**Comment by jailby** [comment]
Some of these (additional) "P" are trigger because there are retrieved from OSM.
Some OSM's contributor created separate parking lot for disable (for example, not only) area within a parking lot.

This is not the right way to do it anymore:
http://wiki.openstreetmap.org/wiki/Proposed_features/parking

OSM should be updated with the tag parking_space which allow contributor to specify tag such as disable for some specific space within a parking lot.
Parking space tag utilization:
http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dparking_space

A quick fix would be to not render the disable parking but some parking would be left out. For example the lot in the loop by ENB and lot 8C.

Another fix could be, instead of rendering a "P" for disable parking lot, a disable parking icon could be rendered.

**Comment by jmfield2** [comment]
I think we can close this since there are no more blue P icons in the map tiles after switching to MapBox. 

There is another issue #292 open to readd them so as long as that issue only adds 1 icon per lot, I suspect it will be fine.

**Comment by barbeau** [comment]
Agreed, closing.
